#!/bin/bash

#SBATCH --nodes=2
#SBATCH --ntasks-per-node=110
#SBATCH --output=alltoall_N2.%j.out
#SBATCH --error=alltoall_N2.%j.err
#SBATCH --account=UNM
#SBATCH --time=00:30:00
#SBATCH --partition=pdebug
#SBATCH --cpus-per-task=1
##SBATCH --mem-per-cpu=25

cd $HOME/AdvanceAlltoall/build/benchmarks
nnodes=2
ppn=110
ntasks=$(( ${nnodes} * ${ppn} ))
echo "Running Alltoall Benchmark on ${nnodes} nodes and ${ntasks} tasks"
srun -n ${ntasks} -N ${nnodes} ./alltoall_topology


